### ISSUE TITLE
System context configured in custom Main class results in ClassCastException 

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-swarm/wildfly-swarm-camel#17]
If I have a custom main class like:

```java
public class Main {
    public static void main(String... args) throws Exception {
        Container container = new Container();
        container.fraction(new CamelCoreFraction().addRouteBuilder(new RouteBuilder() {
                @Override
                public void configure() throws Exception {
                    from("direct:start").to("log:end");
                }
            })
        );
        container.start();
    }
}
```

It leads to:
```

12:10:13,691 INFO  [org.jboss.msc] (main) JBoss MSC version 1.2.6.Final
12:10:13,827 INFO  [org.jboss.as] (MSC service thread 1-6) WFLYSRV0049: WildFly Core 2.0.10.Final "Kenny" starting
2016-03-13 12:10:14,477 INFO  [org.jboss.gravia.runtime] (MSC service thread 1-2) Installed: Module[gravia-system:0.0.0]
2016-03-13 12:10:14,477 INFO  [org.jboss.gravia.runtime] (MSC service thread 1-2) Runtime created: org.wildfly.extension.gravia.service.WildFlyRuntime@792c18e1
2016-03-13 12:10:14,488 INFO  [org.wildfly.extension.camel] (MSC service thread 1-2) Activating Camel Subsystem
2016-03-13 12:10:14,488 INFO  [org.wildfly.extension.gravia] (MSC service thread 1-7) Activating Gravia Subsystem
2016-03-13 12:10:14,491 INFO  [org.jboss.gravia.runtime] (MSC service thread 1-7) Installed: Module[gravia-container-wildfly-extension:1.3.1]
2016-03-13 12:10:14,492 INFO  [org.jboss.gravia.runtime] (MSC service thread 1-7) Started: Module[gravia-container-wildfly-extension:1.3.1]
2016-03-13 12:10:14,493 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-6) MSC000001: Failed to start service jboss.wildfly.swarm.camel.bootstrap: org.jboss.msc.service.StartException in service jboss.wildfly.swarm.camel.bootstrap: java.lang.ClassCastException: org.wildfly.swarm.examples.camel.rest.Main$1 cannot be cast to org.apache.camel.builder.RouteBuilder
	at org.wildfly.swarm.camel.core.runtime.CamelCoreConfiguration$BootstrapCamelContextService.start(CamelCoreConfiguration.java:134)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: org.wildfly.swarm.examples.camel.rest.Main$1 cannot be cast to org.apache.camel.builder.RouteBuilder
	at org.wildfly.swarm.camel.core.runtime.CamelCoreConfiguration$BootstrapCamelContextService.start(CamelCoreConfiguration.java:123)
	... 5 more

2016-03-13 12:10:14,565 ERROR [stderr] (main) Exception in thread "main" org.jboss.msc.service.StartException in service jboss.wildfly.swarm.camel.bootstrap: java.lang.ClassCastException: org.wildfly.swarm.examples.camel.rest.Main$1 cannot be cast to org.apache.camel.builder.RouteBuilder
2016-03-13 12:10:14,565 ERROR [org.jboss.as] (Controller Boot Thread) WFLYSRV0026: WildFly Core 2.0.10.Final "Kenny" started (with errors) in 912ms - Started 36 of 41 services (1 services failed or missing dependencies, 4 services are lazy, passive or on-demand)
2016-03-13 12:10:14,565 ERROR [stderr] (main) 	at org.wildfly.swarm.camel.core.runtime.CamelCoreConfiguration$BootstrapCamelContextService.start(CamelCoreConfiguration.java:134)
2016-03-13 12:10:14,565 ERROR [stderr] (main) 	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
2016-03-13 12:10:14,566 ERROR [stderr] (main) 	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
2016-03-13 12:10:14,566 ERROR [stderr] (main) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2016-03-13 12:10:14,566 ERROR [stderr] (main) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2016-03-13 12:10:14,566 ERROR [stderr] (main) 	at java.lang.Thread.run(Thread.java:745)
2016-03-13 12:10:14,566 ERROR [stderr] (main) Caused by: java.lang.ClassCastException: org.wildfly.swarm.examples.camel.rest.Main$1 cannot be cast to org.apache.camel.builder.RouteBuilder
2016-03-13 12:10:14,567 ERROR [stderr] (main) 	at org.wildfly.swarm.camel.core.runtime.CamelCoreConfiguration$BootstrapCamelContextService.start(CamelCoreConfiguration.java:123)
2016-03-13 12:10:14,567 ERROR [stderr] (main) 	... 5 more
```

**Comment by jamesnetherton** [comment]
Closing this. I think this was happening because I had a mismatch between the camel fraction and other swarm versions

The example seems to be working fine when wildfly-swarm-camel is updated to use swarm core Beta4 and Beta2 of the swarm-fraction plugin.
