### ISSUE TITLE
Investigate why slf4j-log4j12 causes example integration tests to fail

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-swarm/wildfly-swarm-camel#21]
Works fine from a standard `java -jar` execution but fails when integration tests are run.

The presence of slf4j-log4j12 seems to be the culprit and is a ZooKeeper dependency.

```
java.lang.NoClassDefFoundError: org/apache/log4j/Level
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:135)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:114)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:316)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:284)
	at org.wildfly.swarm.camel.core.CamelCoreFraction.<clinit>(CamelCoreFraction.java:33)
	at org.wildfly.swarm.camel.core.runtime.CamelCoreConfiguration.defaultFraction(CamelCoreConfiguration.java:64)
	at org.wildfly.swarm.camel.core.runtime.CamelCoreConfiguration.defaultFraction(CamelCoreConfiguration.java:56)
	at org.wildfly.swarm.container.runtime.RuntimeServer.createDefaultFor(RuntimeServer.java:262)
	at org.wildfly.swarm.container.Container.lambda$applyFractionDefaults$2(Container.java:162)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)

```

**Comment by jamesnetherton** [comment]
I think we have a lot of stuff leaking onto the classpath that we don't really want to be there. Upstream we [exclude various libraries](https://github.com/wildfly-extras/wildfly-camel/blob/23af2625451d543b82d471d87a59a62c17cbc9f5/feature/etc/smartics/wildfly-modules.xml) that are already provided by WildFly.

The `wildfly-swarm-plugin` `start` goal, resolves project dependencies and adds them to the classpath for executing `org.wildfly.swarm.Swarm`. This results in most of the things we want excluded being included on the classpath. E.g we end up with multiple versions of javassist, JAX-RS, JAXB etc. 

The simple means of avoiding this would be to specify `<useUberJar>true</useUberJar>` on the swarm plugin configuration. Else we'd have to look at using Maven exclusions (which would probably be a painful exercise).

**Comment by jamesnetherton** [comment]
Closing as this is no longer relevant.
