### ISSUE TITLE
camel-cdi throws NCDFE with WAR deployment

### ISSUE THREAD

**Issue by tdiesler** [wildfly-swarm/wildfly-swarm-camel#47]
When running `java -jar target/example-camel-jpa-swarm.jar ` I see
```
2016-05-24 16:10:58,185 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-6) MSC000001: Failed to start service jboss.deployment.unit."example-camel-jpa.war".POST_MODULE: org.jboss.msc.service.StartException in service jboss.deployment.unit."example-camel-jpa.war".POST_MODULE: WFLYSRV0153: Failed to process phase POST_MODULE of deployment "example-camel-jpa.war"
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:154)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/apache/camel/core/osgi/utils/BundleContextUtils
	at org.apache.camel.cdi.CdiCamelEnvironment.hasBundleContext(CdiCamelEnvironment.java:56)
	at org.apache.camel.cdi.CdiCamelEnvironment.<init>(CdiCamelEnvironment.java:33)
	at org.apache.camel.cdi.CdiCamelExtension.<init>(CdiCamelExtension.java:77)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.jboss.as.weld.deployment.WeldPortableExtensions.tryRegisterExtension(WeldPortableExtensions.java:53)
	at org.jboss.as.weld.deployment.processors.WeldPortableExtensionProcessor.loadAttachments(WeldPortableExtensionProcessor.java:121)
	at org.jboss.as.weld.deployment.processors.WeldPortableExtensionProcessor.deploy(WeldPortableExtensionProcessor.java:81)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:147)
```

**Comment by tdiesler** [comment]
Extra jars in WEB-INF/lib seem to be causing this

Fixing with `packagingExcludes`

```
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-war-plugin</artifactId>
        <configuration>
          <failOnMissingWebXml>false</failOnMissingWebXml>
          <packagingExcludes>WEB-INF/lib/*.jar</packagingExcludes>
        </configuration>
      </plugin>
```

**Comment by tdiesler** [comment]
duplicates https://issues.jboss.org/browse/SWARM-483
