### ISSUE TITLE
Camel DefaultFinderFactory can't retrieve the swagger service packaged within camel-swagger-java jar

### ISSUE THREAD

**Issue by cmoulliard** [wildfly-swarm/wildfly-swarm-camel#52]
To use swagger with a swarm camel project, I have added this artifact to the pom of the project

```
        <!-- Swarm -->
        <dependency>
            <groupId>org.wildfly.swarm</groupId>
            <artifactId>container</artifactId>
        </dependency>
        <dependency>
            <groupId>org.wildfly.swarm</groupId>
            <artifactId>jaxrs</artifactId>
        </dependency>
        <dependency>
            <groupId>org.wildfly.swarm</groupId>
            <artifactId>jolokia</artifactId>
        </dependency>

        <!-- Camel Swarm -->
        <dependency>
            <groupId>org.wildfly.swarm</groupId>
            <artifactId>camel-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.wildfly.swarm</groupId>
            <artifactId>camel-undertow</artifactId>
        </dependency>

        <!-- Camel -->
        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-swagger-java</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-jackson</artifactId>
        </dependency>
```
Unfortunately, Camel can't retrieve the Class implementing the service 

```
package org.apache.camel.swagger;

import java.util.HashMap;
import java.util.Map;
import org.apache.camel.CamelContext;
import org.apache.camel.Processor;
import org.apache.camel.spi.RestApiProcessorFactory;
import org.apache.camel.spi.RestConfiguration;
import org.apache.camel.swagger.RestSwaggerProcessor;

public class SwaggerRestApiProcessorFactory implements RestApiProcessorFactory {
```
and packaged within the jar camel-swagger-java

![screenshot 2016-06-30 19 37 57](https://cloud.githubusercontent.com/assets/463790/16498139/98f3872a-3efa-11e6-81c0-160adb689247.png)

Error 

```
2016-06-30 19:38:09,790 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-6) MSC000001: Failed to start service jboss.wildfly.swarm.camel.bootstrap: org.jboss.msc.service.StartException in service jboss.wildfly.swarm.camel.bootstrap: org.apache.camel.FailedToCreateProducerException: Failed to create Producer for endpoint: Endpoint[rest-api:///swagger.json?componentName=undertow&routeId=route2]. Reason: java.lang.IllegalStateException: Cannot find RestApiProcessorFactory in Registry or classpath (such as the camel-swagger-java component)
        at org.wildfly.swarm.camel.core.runtime.CamelCoreConfiguration$BootstrapCamelContextService.start(CamelCoreConfiguration.java:134)
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.camel.FailedToCreateProducerException: Failed to create Producer for endpoint: Endpoint[rest-api:///swagger.json?componentName=undertow&routeId=route2]. Reason: java.lang.IllegalStateException: Cannot find RestApiProcessorFactory in Registry or classpath (such as the camel-swagger-java component)
        at org.apache.camel.impl.ProducerCache.doGetProducer(ProducerCache.java:444)
        at org.apache.camel.impl.ProducerCache.acquireProducer(ProducerCache.java:160)
        at org.apache.camel.processor.SendProcessor.doStart(SendProcessor.java:243)
        at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
        at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
        at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:60)
        at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:104)
        at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:90)
        at org.apache.camel.processor.DelegateAsyncProcessor.doStart(DelegateAsyncProcessor.java:79)
        at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
        at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
        at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:60)
        at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:104)
        at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:90)
        at org.apache.camel.processor.RedeliveryErrorHandler.doStart(RedeliveryErrorHandler.java:1372)
        at org.apache.camel.support.ChildServiceSupport.start(ChildServiceSupport.java:44)
        at org.apache.camel.support.ChildServiceSupport.start(ChildServiceSupport.java:31)
        at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
        at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:60)
        at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:104)
        at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:90)
        at org.apache.camel.processor.interceptor.DefaultChannel.doStart(DefaultChannel.java:156)
        at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
        at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
        at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:60)
        at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:104)
        at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:90)
        at org.apache.camel.processor.DelegateAsyncProcessor.doStart(DelegateAsyncProcessor.java:79)
        at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
        at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
        at org.apache.camel.impl.RouteService.startChildService(RouteService.java:340)
        at org.apache.camel.impl.RouteService.warmUp(RouteService.java:182)
        at org.apache.camel.impl.DefaultCamelContext.doWarmUpRoutes(DefaultCamelContext.java:3490)
        at org.apache.camel.impl.DefaultCamelContext.safelyStartRouteServices(DefaultCamelContext.java:3420)
        at org.apache.camel.impl.DefaultCamelContext.doStartOrResumeRoutes(DefaultCamelContext.java:3197)
        at org.apache.camel.impl.DefaultCamelContext.doStartCamel(DefaultCamelContext.java:3053)
        at org.apache.camel.impl.DefaultCamelContext.access$000(DefaultCamelContext.java:175)
        at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:2848)
        at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:2844)
        at org.apache.camel.impl.DefaultCamelContext.doWithDefinedClassLoader(DefaultCamelContext.java:2867)
        at org.apache.camel.impl.DefaultCamelContext.doStart(DefaultCamelContext.java:2844)
        at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
        at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:2813)
        at org.wildfly.swarm.camel.core.runtime.CamelCoreConfiguration$BootstrapCamelContextService.start(CamelCoreConfiguration.java:131)
        ... 5 more
Caused by: java.lang.IllegalStateException: Cannot find RestApiProcessorFactory in Registry or classpath (such as the camel-swagger-java component)
        at org.apache.camel.component.rest.RestApiEndpoint.createProducer(RestApiEndpoint.java:201)
        at org.apache.camel.impl.ProducerCache.doGetProducer(ProducerCache.java:439)
        ... 48 more

```

The DefaultFinderFactory is not able to retrieve the Swagger file located here : META-INF/services/org/apache/camel/rest/ and containing the class to be used : class=org.apache.camel.swagger.SwaggerRestApiProcessorFactory

The problem is that the WildFlyClassResolver of the camel swarm extension only contains 2 classes packaged under org.wildfly.swarm.camel.core. As the classloader only sees these classes, it can't resolve the class SwaggerRestApiProcessorFactory packaged under org.apache.camel.swagger

- Project is available here  : https://github.com/cmoulliard/swarm-camel-demo/
- You can debug with this cmd (port = 5555) -->  mvn wildfly-swarm:run -Pdebug

Questions:
- Is there a trick ?
- Do we have to turn camel-swagger-java into a fraction ?

**Comment by jamesnetherton** [comment]
There is a camel fraction containing swagger-java. You should be able to make things work by adding:

```xml
<dependency>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>camel-other</artifactId>
</dependency>
```

Unfortunately this will bring in a bunch of other camel components. We don't have every camel component mapped to individual fractions yet.

**Comment by cmoulliard** [comment]
I will discuss with Thomas ho we could easily generate from the existing modules their fraction equivalent. Ideally a module should be a fraction and viceversa.

**Comment by cmoulliard** [comment]
There are artifact not found issues when we install `camel-other` fraction

```
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find org.restlet.jee:org.restlet:jar:2.3.6 in http://repository.jboss.org/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of jboss-public-repository-group has elapsed or updates are forced
        at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:232)
        at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:599)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:518)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:436)
        ... 44 more
ERR org.eclipse.aether.resolution.ArtifactResolutionException: Failure to find org.restlet.jee:org.restlet.ext.httpclient:jar:2.3.6 in http://repository.jboss.org/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of jboss-public-repository-group has elapsed or updates are forced
org.eclipse.aether.resolution.ArtifactResolutionException: Failure to find org.restlet.jee:org.restlet.ext.httpclient:jar:2.3.6 in http://repository.jboss.org/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of jboss-public-repository-group has elapsed or updates are forced
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:459)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:262)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:239)
        at org.wildfly.swarm.plugin.maven.MavenArtifactResolvingHelper.resolve(MavenArtifactResolvingHelper.java:89)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.wildfly.swarm.plugin.maven.MavenArtifactResolvingHelper.resolveAll(MavenArtifactResolvingHelper.java:157)
        at org.wildfly.swarm.tools.DependencyManager.resolveAllArtifacts(DependencyManager.java:512)
        at org.wildfly.swarm.tools.DependencyManager.analyzeDependencies(DependencyManager.java:257)
        at org.wildfly.swarm.tools.BuildTool.analyzeDependencies(BuildTool.java:223)
        at org.wildfly.swarm.tools.BuildTool.build(BuildTool.java:176)
        at org.wildfly.swarm.tools.BuildTool.build(BuildTool.java:171)
        at org.wildfly.swarm.plugin.maven.PackageMojo.execute(PackageMojo.java:121)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions(MojoExecutor.java:364)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:198)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find org.restlet.jee:org.restlet.ext.httpclient:jar:2.3.6 in http://repository.jboss.org/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of jboss-public-repository-group has elapsed or updates are forced
        at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:232)
        at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:599)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:518)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:436)
        ... 44 more
[WARNING] The POM for org.restlet.jee:org.restlet.ext.httpclient:jar:2.3.6 is missing, no dependency information available
[WARNING] The POM for org.restlet.jee:org.restlet:jar:2.3.6 is missing, no dependency information available
```

**Comment by jamesnetherton** [comment]
Yes, an unfortunate side effect of having multiple components grouped together in a single fraction. I think adding the following repository will resolve it:

```
  <repositories>
    <repository>
      <id>springsource-libs-releases</id>
      <url>http://repo.springsource.org/libs-release-remote</url>
    </repository>
  </repositories>
```

**Comment by cmoulliard** [comment]
If I change the version of camel to 2.17.1 and recompile the swarm camel project 1.1.0, then I can launch wildfly even if a warning is displayed.

```
[INFO] --- wildfly-swarm-plugin:1.0.0.Final:package (default) @ swarm-camel-rest ---
[WARNING] The POM for org.restlet.jee:org.restlet.ext.httpclient:jar:2.3.6 is missing, no dependency information available
[WARNING] The POM for org.restlet.jee:org.restlet:jar:2.3.6 is missing, no dependency information available
```

Nevertheless the problem reported here is still there as the `SwaggerRestApiProcessorFactory ` is not found

Remark : I have opened a ticket to align the camel version of swarm-camel to 2.1.7.1 which corresponds to the version available in wildfly-camel 4.1.0

**Comment by cmoulliard** [comment]
FYI: Here is the content of the uberJar. As you can see it contains the camel-swagger jar

https://gist.github.com/cmoulliard/dde104bb817fbc67675a7926e42218d8

**Comment by jamesnetherton** [comment]
Looks like a bug - the same route seems to run fine when run with the standard WildFly-Camel.

**Comment by tdiesler** [comment]
Cannot reproduce. This seems to work fine.
https://issues.jboss.org/browse/SWARM-539

**Comment by cmoulliard** [comment]
The classloading issue is there. So this ticket shouldn't close. The SWARM-539 example works because it uses camel-cdi

**Comment by tdiesler** [comment]
Again, please start with something that works and show me a (valid) commit that actually breaks it. [Here](https://github.com/tdiesler/wildfly-swarm-examples/tree/SWARM-539) I can show that the Camel Swagger + Rest example works with and without the help of CDI.

**Comment by jamesnetherton** [comment]
But now you're cheating with Spring instead of CDI :wink: 

The code sample uses the Camel Fraction to add the RouteBuilder:

https://github.com/cmoulliard/swarm-camel-demo/blob/master/src/main/java/io/fabric8/quickstarts/swarm/MainApp.java#L31-L32

**Comment by tdiesler** [comment]
Spring package scan functionality is part of camel-core.

This update shows, is that camel swagger + rest works on undertow with a minimum of

```
    <dependency>
      <groupId>org.wildfly.swarm</groupId>
      <artifactId>camel-undertow</artifactId>
    </dependency>
    <dependency>
      <groupId>org.wildfly.swarm</groupId>
      <artifactId>camel-other</artifactId>
    </dependency>
```

The RouteBuilder is part of the (default) deployment. It is discovered and activated as part of the normal DU processing. It is also the most straight forward approach that we use in (almost) all non swarm tests/examples.

An approach like this

```
        new Container()
            .fraction(new CamelCoreFraction().addRouteBuilder(new SwaggerRouteBuilder()))
            .start(true).deploy();
```  

is awkward and it is perhaps not terrible obvious why this can hardly work.

This syntax attempts to add a system camel context to the wildfly bootstrap configuration. Types used in such a configuration must be visible to the camel subsystem at wildfly startup time. We have very few tests that actually do this and although I'm fairly sure that system contexts support types that come from camel components, I would need to double check that.

System contexts can however never support types that come from some flat bootstrap class path, that does not have the required dependencies on the module hierarchy. IIRC, we have hooks into the camel subsystem module def that would allow additional user defined modules to become visible to the subsystem, which however is not the case here.

Having said this, let me look at this a little further - `CamelCoreFraction.addRouteBuilder()` certainly needs better docs on what can actually be expected to work.

**Comment by tdiesler** [comment]
Investigating: Cannot use rest API in system context
https://github.com/wildfly-extras/wildfly-camel/issues/1242

**Comment by tdiesler** [comment]
This now depends on wildfly-camel-4.2.0 and https://issues.jboss.org/browse/SWARM-546
